dist: xenial
language: php

services:
  - postgresql

addons:
  postgresql: "13"

before_install:
  - sudo apt-get update
  - sudo apt-get install -y unzip git zip libzip-dev libpq-dev openjdk-17-jdk
  - java -version

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    - PATH=$JAVA_HOME/bin:$PATH
    - DB_CONNECTION=pgsql
    - DB_HOST=127.0.0.1
    - DB_PORT=5432
    - DB_DATABASE=travis_ci_laravel
    - DB_USERNAME=postgres
    - DB_PASSWORD=
    - TOKEN_SONAR=[secure]

install:
  - composer install --no-interaction --prefer-dist --optimize-autoloader

before_script:
  - sudo service postgresql restart
  - sleep 10
  - psql -c "CREATE DATABASE travis_ci_laravel;" -U postgres
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate --force

script:
  - ./vendor/bin/phpunit --coverage-clover=storage/coverage.xml

after_success:
  - curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
  - unzip sonar-scanner.zip
  - export PATH="$PWD/sonar-scanner-4.7.0.2747-linux/bin:$PATH"
  - sonar-scanner
