language: php
php:
  - 7.3

services:
  - postgresql

addons:
  postgresql: "13"
  sonarcloud:
    organization: "layla-paula"
    token:
      secure: "${SONAR_TOKEN}"

env:
  global:
    - DB_CONNECTION=pgsql
    - DB_HOST=127.0.0.1
    - DB_PORT=5432
    - DB_DATABASE=travis_ci_laravel
    - DB_USERNAME=postgres
    - DB_PASSWORD=

before_install:
  - sudo apt-get update
  - sudo apt-get install -y unzip git zip libzip-dev libpq-dev

install:
  - composer install --no-interaction --prefer-dist --optimize-autoloader

before_script:
  - psql -c "CREATE DATABASE travis_ci_laravel;" -U postgres
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate --force

script:
  - ./vendor/bin/phpunit --coverage-clover=storage/coverage.xml
  - |
    curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
    unzip sonar-scanner.zip
    export PATH="$PWD/sonar-scanner-4.7.0.2747-linux/bin:$PATH"
    sonar-scanner
