language: php

php:
  - 7.3

services:
  - postgresql

before_install:
  - sudo apt-get update
  - sudo apt-get install -y unzip git zip libzip-dev libpq-dev
  - sudo docker --version

install:
  - composer install --no-interaction --prefer-dist --optimize-autoloader

before_script:
  - psql -c "CREATE DATABASE travis_ci_laravel;" -U postgres
  - cp .env.example .env
  - php artisan key:generate
  - php artisan migrate
  - php artisan db:seed --class=UserTableSeeder
  - php artisan db:seed --class=TermTypesTableSeeder
  - php artisan db:seed --class=TermsTableSeeder

script:
  - php artisan test || true
  - sonar-scanner -Dsonar.projectKey=travisTeste -Dsonar.sources=. -Dsonar.host.url=http://localhost:9000 -Dsonar.login=$SONAR_TOKEN

env:
  global:
    - DB_CONNECTION=pgsql
    - DB_HOST=127.0.0.1
    - DB_PORT=5432
    - DB_DATABASE=travis_ci_laravel
    - DB_USERNAME=postgres
    - DB_PASSWORD=

addons:
  postgresql: "13"

cache:
  directories:
    - $HOME/.composer/cache
