

services:
  app:
    build: .
    container_name: laravel_app
    working_dir: /var/www/html
    ports:
      - "8000:80"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres


  postgres:
    image: postgres:13
    container_name: pgsql
    restart: always
    environment:
      POSTGRES_DB: travis_ci_laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
